In [66]:
import numpy as pd
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Bidirectional, Dense, Dropout
from tensorflow.keras.optimizers import Adam


In [8]:
df=pd.read_csv("Landslide Civildf_new.csv")

In [9]:
df.head()

Unnamed: 0            Timestamp  Rainfall  Water level   Inc30mup  \
0           0  2022-12-01 01:00:00       0.0  -177.753910  24.520339   
1           1  2022-12-01 02:00:00       0.0  -104.417316  26.093114   
2           2  2022-12-01 03:00:00       0.0  -158.065690  29.426647   
3           3  2022-12-01 04:00:00       0.0  -189.458110  30.382570   
4           4  2022-12-01 05:00:00       0.0  -197.408960  25.493729   

   Inc 30m down   Inc 20m up   Inc 20m down  Inc 10m up  Inc 10m down  \
0      31.058241    16.023206     26.345443   20.637553     25.830825   
1      37.702314    15.116429     36.349078   20.836093     29.274305   
2      27.552242    20.673672     31.637946   20.879557     26.278678   
3      34.624852    21.397603     27.999477   22.426564     25.463844   
4      29.837320    18.103459     31.207890   23.932405     28.861409   

   1st Tensiometer  2nd Tensiometer  3rd Tensiometer   4th Tensiometer  \
0       -48.832508       -49.926434         181.57994        -3.156536   
1       -48.868384       -49.929076         181.60057        -3.142777   
2       -48.895732       -49.930162         181.61358        -3.129418   
3       -48.914294       -49.932082         181.61197        -3.137719   
4       -48.914736       -49.932394         181.62403        -3.137719   

   5th Tensiometer  
0       -48.597010  
1       -48.629946  
2       -48.652374  
3       -48.671676  
4       -48.673116

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        696 non-null    int64  
 1   Timestamp         696 non-null    object 
 2   Rainfall          696 non-null    float64
 3   Water level       696 non-null    float64
 4   Inc30mup          696 non-null    float64
 5   Inc 30m down      696 non-null    float64
 6   Inc 20m up        696 non-null    float64
 7   Inc 20m down      696 non-null    float64
 8   Inc 10m up        696 non-null    float64
 9   Inc 10m down      696 non-null    float64
 10  1st Tensiometer   696 non-null    float64
 11  2nd Tensiometer   696 non-null    float64
 12  3rd Tensiometer   696 non-null    float64
 13  4th Tensiometer   696 non-null    float64
 14  5th Tensiometer   696 non-null    float64
dtypes: float64(13), int64(1), object(1)
memory usage: 81.7+ KB


In [11]:
features = df.drop(columns=['Timestamp','5th Tensiometer'],axis=1)
target=df['5th Tensiometer']

In [14]:
#Standarization
scaler = StandardScaler()
features_standarized=scaler.fit_transform(features)
features_standarized

array([[-1.72956401, -0.12415269, -0.66883956, ..., -0.32298425,
        -1.77207431, -0.50104039],
       [-1.72458685, -0.12415269, -0.4710909 , ..., -0.41201051,
        -1.61621225, -0.28289283],
       [-1.71960969, -0.12415269, -0.61575121, ..., -0.44860495,
        -1.51792017, -0.07109493],
       ...,
       [ 1.71960969, -0.12415269, -0.01582525, ..., -1.06208418,
         1.45675607,  1.19431785],
       [ 1.72458685, -0.12415269, -0.34586704, ..., -1.1203118 ,
         1.52973851,  1.44379355],
       [ 1.72956401, -0.12415269, -0.49975235, ..., -1.16681303,
         1.59093495,  1.54941505]])

In [15]:
#Splitting Dataset
X_train, X_test, y_train, y_test = train_test_split(features_standarized, target, test_size=0.25, random_state=42)

In [16]:
X_train

array([[-0.91828651, -0.12415269, -0.58714365, ...,  0.25066566,
        -0.71941985, -0.59170333],
       [ 0.89837785, -0.12415269, -0.73058854, ..., -0.78590733,
         0.8938243 ,  0.68308728],
       [ 1.30152803, -0.12415269, -0.14480504, ..., -0.26105001,
         0.99589393,  0.68907229],
       ...,
       [-0.3857301 , -0.12415269, -0.07126468, ..., -0.89184925,
         0.55573281,  1.08726154],
       [ 0.43550173, -0.12415269, -0.38206701, ..., -0.89319711,
         0.86405714,  0.55522217],
       [-1.22189343, -0.12415269, -0.17935243, ..., -0.86711599,
        -0.14371993,  1.06772901]])

In [17]:
X_test

array([[ 1.6250436 , -0.12415269, -0.14942021, ..., -1.32174972,
         1.74437938,  1.86267269],
       [-0.16673495, -0.12415269, -0.42938059, ..., -0.740417  ,
         0.43802409,  0.7744716 ],
       [ 1.31148235, -0.12415269, -0.18681942, ..., -0.32851048,
         0.85846635,  0.38328997],
       ...,
       [ 1.00787543, -0.12415269, -0.42691221, ..., -0.73954089,
         0.97617508,  0.76086067],
       [-0.86353772, -0.12415269, -0.56315176, ..., -1.07003656,
         0.41165673,  1.42027366],
       [ 1.51554602, -0.12415269,  0.03806099, ..., -1.36622916,
         1.69368455,  1.59614567]])

In [19]:
y_train

163   -48.431280
528   -48.795172
609   -48.624546
436   -48.821596
344   -48.596044
         ...    
71    -48.677400
106   -48.006228
270   -48.836298
435   -48.817610
102   -48.837084
Name: 5th Tensiometer, Length: 522, dtype: float64

In [20]:
y_test

674   -49.014426
314   -48.779206
611   -48.628022
431   -48.804524
552   -48.850660
         ...    
215   -48.781244
635   -48.516480
550   -48.775872
174   -48.922416
652   -49.028972
Name: 5th Tensiometer, Length: 174, dtype: float64

In [21]:
#Reshaping data
timesteps=1
features_count=X_train.shape[1]
X_train_reshaped=X_train.reshape(X_train.shape[0],timesteps,features_count)
X_test_reshaped=X_test.reshape(X_test.shape[0],timesteps,features_count)

In [22]:
X_train_reshaped

array([[[-0.91828651, -0.12415269, -0.58714365, ...,  0.25066566,
         -0.71941985, -0.59170333]],

       [[ 0.89837785, -0.12415269, -0.73058854, ..., -0.78590733,
          0.8938243 ,  0.68308728]],

       [[ 1.30152803, -0.12415269, -0.14480504, ..., -0.26105001,
          0.99589393,  0.68907229]],

       ...,

       [[-0.3857301 , -0.12415269, -0.07126468, ..., -0.89184925,
          0.55573281,  1.08726154]],

       [[ 0.43550173, -0.12415269, -0.38206701, ..., -0.89319711,
          0.86405714,  0.55522217]],

       [[-1.22189343, -0.12415269, -0.17935243, ..., -0.86711599,
         -0.14371993,  1.06772901]]])

In [23]:
X_test_reshaped

array([[[ 1.6250436 , -0.12415269, -0.14942021, ..., -1.32174972,
          1.74437938,  1.86267269]],

       [[-0.16673495, -0.12415269, -0.42938059, ..., -0.740417  ,
          0.43802409,  0.7744716 ]],

       [[ 1.31148235, -0.12415269, -0.18681942, ..., -0.32851048,
          0.85846635,  0.38328997]],

       ...,

       [[ 1.00787543, -0.12415269, -0.42691221, ..., -0.73954089,
          0.97617508,  0.76086067]],

       [[-0.86353772, -0.12415269, -0.56315176, ..., -1.07003656,
          0.41165673,  1.42027366]],

       [[ 1.51554602, -0.12415269,  0.03806099, ..., -1.36622916,
          1.69368455,  1.59614567]]])

In [69]:
# Assuming 'X_train' and 'y_train' are your training data and labels
# Assuming 'X_test' and 'y_test' are your testing data and labels

# Define the model
model = Sequential()
model.add(Bidirectional(LSTM(512, return_sequences=True), input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Bidirectional(LSTM(512, return_sequences=True)))
model.add(Dropout(0.5))

# Compile the model
model.compile(optimizer=Adam(), loss='mse')
model.summary()


IndexError: tuple index out of range

In [60]:
#Bi-directional LSTM Model
input_shape=(timesteps,features_count)
units=512
model=Sequential()
model.add(Bidirectional(LSTM(units,return_sequences=True,input_shape=input_shape)))
model.add(Dropout(0.5))
model.add(Bidirectional(LSTM(units,return_sequences=True,go_backwards=True)))
model.add(Dropout(0.5))
model.add(Bidirectional(LSTM(192, return_sequences=True)))
model.add(Dropout(0.5))
model.add(Bidirectional(LSTM(32, return_sequences=True)))
model.add(Dropout(0.5))
model.add(Bidirectional(LSTM(96, return_sequences=True)))
model.add(Dropout(0.5))
model.add(Dense(1,activation='linear'))
#Building Model
model.build((None,*input_shape))
model.compile(optimizer='adam',loss='mse')

In [61]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional_16 (Bidirect  (None, 1, 1024)           2154496   
 ional)                                                          
                                                                 
 dropout_2 (Dropout)         (None, 1, 1024)           0         
                                                                 
 bidirectional_17 (Bidirect  (None, 1, 1024)           6295552   
 ional)                                                          
                                                                 
 dropout_3 (Dropout)         (None, 1, 1024)           0         
                                                                 
 bidirectional_18 (Bidirect  (None, 1, 384)            1869312   
 ional)                                                          
                                                      

In [63]:
#Training model
model.fit(X_train_reshaped,y_train,epochs=1,batch_size=697,validation_data=(X_test_reshaped,y_test))

1/1 [==============================] - 0s 330ms/step - loss: 2354.7739 - val_loss: 2354.4236


In [64]:
#Model before making predictions
model.build(X_test_reshaped.shape)
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional_16 (Bidirect  (None, 1, 1024)           2154496   
 ional)                                                          
                                                                 
 dropout_2 (Dropout)         (None, 1, 1024)           0         
                                                                 
 bidirectional_17 (Bidirect  (None, 1, 1024)           6295552   
 ional)                                                          
                                                                 
 dropout_3 (Dropout)         (None, 1, 1024)           0         
                                                                 
 bidirectional_18 (Bidirect  (None, 1, 384)            1869312   
 ional)                                                          
                                                      

In [65]:
#Predicitons
predictions=model.predict(X_test_reshaped)
predictions=predictions.reshape(predictions.shape[0],-1)
#Evaluating Model
from sklearn.metrics import mean_absolute_error,r2_score
mse=mean_absolute_error(y_test,predictions)
r2=r2_score(y_test,predictions)
print(f'Mean Squared Error on Test Data:{mse}')
print(f'R2 Score on Test Data:{r2}')

6/6 [==============================] - 4s 9ms/step
Mean Squared Error on Test Data:48.521222676527415
R2 Score on Test Data:-20528.599813332155
